### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by d0ubl3puls4r** [z00z/ZLogger#3]
When executing the script informing the parameters needed for the file creation, I received the following error message:

**Traceback (most recent call last):
  File "zlogger.py", line 39, in <module>
    compile_for_windows(arguments.out)
  File "zlogger.py", line 30, in compile_for_windows
    subprocess.call(["wine", WINDOWS_PYTHON_INTERPRETER_PATH, "--onefile", "--noconsole", file_name])
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory**

How to solve this problem.
Thank you very much in advance

**Comment by HarshitRuwali** [comment]
If you are running the program in windows or Mac then you have to edit the couple of lines. 
You have to add `shell=True` at the end of the subprocess.call. 
For eg.
`subprocess.call(["wine", WINDOWS_PYTHON_INTERPRETER_PATH, "--onefile", "--noconsole", file_name], shell=True)`
And if running in Kali linux, you don't have to make any changes in the program.
